### ISSUE TITLE
call the language extempore rather than xtlang

### ISSUE THREAD

**Issue by benswift** [highlightjs/highlightjs-xtlang#1]
Can we change the top-level naming stuff for this language to be `extempore` rather than `xtlang`?

The reason is that Extempore includes both Scheme and xtlang, and so calling the whole thing `xtlang` (e.g. in `hljs.registerLanguage('xtlang', ...)` is too confusing.

I guess this means that we'll change the filename to `extempore.js`. I realise that the repo itself is called `highlightjs-xtlang`, but I don't think we need to change that for now - the intention is clear.

**Comment by cyblue9** [comment]
OK, I agree.
Please fix it freely!

**Comment by cyblue9** [comment]
Fixed with 89aae475e7170602470eda3ffae770d49d679435.
