### ISSUE TITLE
lexemes doesn't do anything

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlightjs-xtlang#6]
`lexemes` doesn't do anything unless paired with `keywords` which you aren't using (that I can see).  So you could remove it entirely.

**Comment by benswift** [comment]
Thanks @joshgoebel . @cyblue9 I guess this is because we might move to using them in the future? Tbh it's working pretty well at the moment, so I don't think changing it is a high priority with your/my limited time :)

**Comment by benswift** [comment]
So I guess we could remove the lexemes stuff just to avoid confusion.

**Comment by cyblue9** [comment]
@joshgoebel @benswift 

Sorry for late response.
Thank you for advice.
At the time of writing this source, I didn't understand how to use "lexemes".
Perhaps it's okay to remove the `lexeme`.
I will commit this weekend!

**Comment by joshgoebel** [comment]
It only affects keywords, and now it's been replaced by `keywords.$pattern`, to make this clearer.

**Comment by cyblue9** [comment]
@joshgoebel 
Hmm, I read highlightjs docs. I understood how to use `keywords.$pattern`(old `lexeme`).
It's doesn't do anything in this source.
I removed `lexeme`  at [`bdb27b37c86c968371288062052e2a5ad4190a47`](https://github.com/highlightjs/highlightjs-extempore/commit/bdb27b37c86c968371288062052e2a5ad4190a47).
Please review!

**Comment by cyblue9** [comment]
@benswift 
Is it OK of syntax highlight in extempore docs ?
(I checked it myself)
